spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

rabbitmq:
  queue:
    analysisRequest: analysis-request-queue
    analysisResult: analysis-result-queue
    analysisRetry: analysis-retry-queue
    analysisRequestDLQ: analysis-request-dlq
    analysisResultDLQ: analysis-result-dlq

  exchange:
    analysisRequest: analysis-request-exchange
    analysisResult: analysis-result-exchange
    analysisRetry: analysis-retry-exchange
    analysisRequestDLX: analysis-request-dlX
    analysisResultDLX: analysis-result-dlX

  routing-key:
    analysisRequest: analysis-request-routing-key
    analysisResult: analysis-result-routing-key
    analysisRetry: analysis-retry-routing-key
    analysisRequestDLR: analysis-request-dlR
    analysisResultDLR: analysis-result-dlR